---
apiVersion: networking.istio.io/v1alpha3
kind: ServiceEntry
metadata:
  name: yahoo-sports-egress
spec:
  hosts:
  - sports.yahoo.com
  ports:
    - number: 443
      name: https-port
      protocol: https
  resolution: DNS
  location: MESH_EXTERNAL
---
apiVersion: networking.istio.io/v1alpha3
kind: VirtualService
metadata:
  name: yahoo-sports-egress
spec:
  hosts:
  - sports.yahoo.com
  tls:
  - match:
    - port: 443
      sni_hosts:
      - sports.yahoo.com
    route:
    - destination:
        host: sports.yahoo.com
        port:
          number: 443
      weight: 100
---
apiVersion: networking.istio.io/v1alpha3
kind: ServiceEntry
metadata:
  name: yahoo-login-egress
spec:
  hosts:
  - api.login.yahoo.com
  ports:
    - number: 443
      name: https-port
      protocol: https
---
apiVersion: networking.istio.io/v1alpha3
kind: VirtualService
metadata:
  name: yahoo-login-egress
spec:
  hosts:
  - api.login.yahoo.com
  tls:
  - match:
    - port: 443
      sni_hosts:
      - api.login.yahoo.com
    route:
    - destination:
        host: api.login.yahoo.com
        port:
          number: 443
      weight: 100
---
apiVersion: networking.istio.io/v1alpha3
kind: ServiceEntry
metadata:
  name: yahoo-query-egress
spec:
  hosts:
  - query.yahooapis.com
  ports:
    - number: 443
      name: https-port
      protocol: https
---
apiVersion: networking.istio.io/v1alpha3
kind: VirtualService
metadata:
  name: yahoo-query-egress
spec:
  hosts:
  - query.yahooapis.com
  tls:
  - match:
    - port: 443
      sni_hosts:
      - query.yahooapis.com
    route:
    - destination:
        host: query.yahooapis.com
        port:
          number: 443
      weight: 100
---
apiVersion: networking.istio.io/v1alpha3
kind: ServiceEntry
metadata:
  name: yahoo-fsports-egress
spec:
  hosts:
  - fantasysports.yahooapis.com
  ports:
    - number: 443
      name: https-port
      protocol: https
---
apiVersion: networking.istio.io/v1alpha3
kind: VirtualService
metadata:
  name: yahoo-fsports-egress
spec:
  hosts:
  - fantasysports.yahooapis.com
  tls:
  - match:
    - port: 443
      sni_hosts:
      - fantasysports.yahooapis.com
    route:
    - destination:
        host: fantasysports.yahooapis.com
        port:
          number: 443
      weight: 100